# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 481fc282296809f0eb35a9084355bc7b792d1da6fa45a99d77987abe3b130459fc5f843d15fa81d8fe845a3eac0d8b4bbe1b40a1c6cbfb0bfd4cb1d3643ce476

test:
  secret_key_base: 631dc635637d023c58cd8a514b4caf67cb4ca2cb128b6f779f31e3e1769a73d1ab312ece9f3ed03f5e82d3993791c2c3ef6ecfd5194ed3739c54a3fb29430929

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
